### PR TITLE
low profile enclosure

### LINKED ISSUE #12: [Feature Request] Increase hole diameter of top enclosure casing from 3.2 to 3.5 mm
<a href="https://107-systems.org/"></a>

### ⚡ Feature Request

Currently the diameter is at 3.2 mm, should be increased to 3.5 mm (no cutting screws used).

image

### LINKED ISSUE #13: [Feature Request] Reduce overall height of bottom enclosure from 25 mm to 15 mm
<a href="https://107-systems.org/"></a>

### ⚡ Feature Request

Please re-design the top accordingly, this needs the planning of cut-outs where the capacitory are placed. With a total height of 15 mm the power-pole connectors should be firmly squeezed in place by the top enclosure.

### PR DESCRIPTION
**Pull request by generationmake**
generate a low profile enclosure with a reduced height (-9mm)

### CODE REVIEW

**Review by aentinger — COMMENTED** [review]
This looks good to me, I'll run a test-print.

**Comment by generationmake** [comment]
@aentinger yes, please do so!

**Comment by aentinger** [comment]
The bottom print went fine, but the one for the top proved problematic. The distance between the outer border and the long cut-out is very small leading to print problems.




IMG_20230120_115631_120

@generationmake any idea how the design could be improved?
@wuehr1999 any idea how manufacturing could be improved?

**Comment by aentinger** [comment]
Printing remains an issue but the diameter of the singular caps is definitely to small. Please increase it.

**Comment by aentinger** [comment]
IMG_20230120_203649_187

**Comment by aentinger** [comment]
Recreate a lip with a length of 5 mm (measured from the top).

**Comment by wuehr1999** [comment]
Hi @aentinger, it seems that the distance of the printing nozzle and the bed is a little bit too high for the first layer. For PLA I use a bed temperature of 60° and a nozzle temperature of 210°. I can also recommend [3DLAC](https://www.3dlac.com/).
I could provide a PrusaSlicer project for the power injector case to give You a better start.

**Comment by aentinger** [comment]
Hi @wuehr1999 :coffee: :wave: 

I've uploaded the PrusaSlicer project files ... feel free to fine-tune.

@generationmake will still need to re-generate an STL file with a bigger diameter for the single electrolytic caps.

**Comment by generationmake** [comment]
Hi @aentinger 
I updated the data for the upper half and increased the diameter for the capacitors. maybe I placed them a little bit off center and this leads to problems now.
I also added a lip near the CAN connectors.

Maybe you could test it again? Thanks

**Comment by aentinger** [comment]
I'm fighting with my 3D printer -.- 

@wuehr1999 could you please prove a PrusaSlicer project for the top enclosure with the best settings from your perspective?

**Comment by aentinger** [comment]
Perfect design, thank you @generationmake 🚀 

IMG_20230124_102624_217
IMG_20230124_102619_255
IMG_20230124_102611_244

**Review by aentinger — APPROVED** [review]
LGTM :+1: Thank you @generationmake :coffee: :wave:

**Comment by generationmake** [comment]
very nice print! 👍

**Pull request merged**
