### PR TITLE
Enclosure

### PR DESCRIPTION
**Pull request by generationmake**

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @aentinger and @wuehr1999 
I designed an enclosure for the PCB. The PCB needs to be screwed in. Could you please check the data?
Until now I don't have a snapping mechanism to keep top and bottom together. I don't know if we need it.
And I don't know if the holes for the connectors are big enough.
What do you think?
Thanks

**Comment by aentinger** [comment]
Hi @generationmake ☕ 👋 

Thank you for the design! I'll take a look and will get back to you. Re snapping mechanism: that would be preferred but we could also screw it together? What do you think?

**Comment by wuehr1999** [comment]
Hi @generationmake,
lgtm.
I would add some hexagonal holes for nuts on the bottom. A snapping mechanism sounds good. As an alernative, screwing holes could be added in order to screw both case parts and the PCB together with 4 screws and spacers.

**Review by aentinger — CHANGES_REQUESTED** [review]
Hi @generationmake :coffee: :wave:

Thank you for your this neat design :wink: . I've just checked it and found an issue with it: The electrolytic caps that I've ordered are of a different type compared to the ones you put into the design. Those caps have a height of 17 mm (see [here](https://www.digikey.at/en/products/detail/vishay-beyschlag-draloric-bc-components/MAL215097102E3/5635408)).

This is a problem because in the enclosure design a maximum height of 10 mm is assumed:

Screenshot from 2023-01-07 21-06-27

Other than that I second @wuehr1999 suggestion for adding some hexagonal holes for nuts on the bottom. The top cover could go down in such a way that the PCB is sandwiched between the top and the bottom enclosure, with a screw inserted from the top is holding everything together.

**Comment by generationmake** [comment]
Hi @aentinger and @wuehr1999 
I added the changes...
The capacitors you ordered are 14 mm high. But we are not limited by height so I increased the height of the enclosure so that 17 mm capacitors should also fit in.

**Comment by aentinger** [comment]
>The capacitors you ordered are 14 mm high.

Hugh. Good that you've checked that. So Digikey's product page is lying.

**Review by aentinger — APPROVED** [review]
I've reviewed the files and they look good to me! Great work @generationmake ! :rocket: PR can be merged from my perspective, will do test print during the week.

**Comment by aentinger** [comment]
Somehow I think that the exported STL for the top does not match the one within FreeCAD oO 😕 .

@generationmake can you please check?

IMG_20230111_162315_619
IMG_20230111_162259_463

**Comment by generationmake** [comment]
Hi @aentinger 
the top-ecnlosure you printed does not match the stl file.
Please check with the simulator on github.
Maybe you mirrored it while preparing to print?

**Comment by aentinger** [comment]
> Maybe you mirrored it while preparing to print?

I might have. Will double-check.

**Comment by aentinger** [comment]
Looking good @generationmake 👍

**Comment by generationmake** [comment]
@aentinger 👍 
very nice.
the first pcb is also ready:
IMG_20230113_175002

**Comment by aentinger** [comment]
Terrific! Looks great!

**Comment by aentinger** [comment]
Works, but a couple of design adjustments are needed, I'll open issues.

**Pull request merged**
