### PR TITLE
Development of v0.1 of the CAN Power Injector.

### PR DESCRIPTION
**Pull request by aentinger**
Hi @generationmake :coffee: :wave:

In order to get rid of a ton of additional cabling on the L3X-Z hexapod I'll be needing a circuit which allows me to provide 5V/3A via the CAN VCC line to supply all the downstream power consumers. Could you design such a board :pray:?

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @aentinger 
Shure!
Can we devine the input voltage range? I would suggest 7 - 30 V.

**Comment by aentinger** [comment]
Great! My first idea was in the range of 13.0 - 16.8 V (empty to full 4S LiFePo4 battery), see [here](https://github.com/107-systems/l3xz-hw_can_power_injector/tree/dev_v0.1#electrical-parameters). However, a much larger dynamic range won't be a disadvantage.

**Comment by generationmake** [comment]
possible voltage regulators:
https://www.ti.com/product/LMR51430
https://www.ti.com/product/LMR33630

**Comment by generationmake** [comment]
https://www.analog.com/en/products/lt8610a.html#product-overview

**Comment by aentinger** [comment]
Hi @generationmake ☕ :wave:

They all look suitable (not sure if the LT8610's constraint on 5V or 3V3 only gives it superior performance over the TI parts on some aspects). I did a quick check re availability:
* LMR51430 :x: 
* LMR33630 ❌ 
* LT8610A ✔️

**Comment by generationmake** [comment]
https://www.renesas.com/eu/en/products/power-power-management/dc-dc-converters/step-down-buck/buck-regulators-integrated-fets/raa211650-60v-5a-integrated-switching-regulator

**Comment by aentinger** [comment]
That one (RAA211650) seems to be a quite a best - and one that you can even buy ✔️

**Comment by generationmake** [comment]
@aentinger 
basic layout is finished.
Comments please ;-)

**Comment by aentinger** [comment]
Hi @generationmake ☕ :wave:

Thank you very much for your work 👍 .

A couple of points:

* Both CN2 and CN3 connect pin 1 to net VCC. That's an issue as the Zubax Babel provides itself 5V on pin 1 leading to a tug-of-war between the Babel and the Buck-Converter (which the Buck-Converter is going to win and the Babel is going to go up in smoke). Only connect one JST connector to pin 1.

* Please place M2.5 holes on each corner of the PCB for mounting.

* Please use right-angle PCB contacts for mounting the AndersonPowerPole connector (see [datasheet](https://www.andersonpower.com/content/dam/app/ecommerce/product-pdfs/DS-PP1545.pdf), part numbers [1317G1](https://www.digikey.at/en/products/detail/anderson-power-products-inc/1317G1/10650514 )and [1317G2](https://www.digikey.at/en/products/detail/anderson-power-products-inc/1317G2/10650060)).

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave:

How's development going? :wink: Can I send smth to manufacturing?

**Comment by generationmake** [comment]
Hi @aentinger 
Layout is done.
Could you please check?
Thanks

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave:
Thank you very much for your work :bow: . The board looks great!

One question though:
* Why are **C8**/**C10** connected to **VCC** (and not **CAN1VCC**/**CAN2VCC**)? Placement on the schematic next to **C9**/**C11** suggests connecting them to **CAN1VCC**/**CAN2VCC**, also there are already large sized caps (**C14**/**C16**) buffering **VCC**.

**Comment by aentinger** [comment]
Other than that I believe we can move ahead with manufacturing :+1:

**Comment by aentinger** [comment]
Ping @generationmake :coffee: :wave:

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave:

Is the BOM good for ordering?

**Comment by aentinger** [comment]
I've ordered all parts as agreed. Note: [ECC MZL500ARA221](https://www.reichelt.com/de/en/electrolytic-capacitor-smd-220-f-50-v-105-c-low-esr-10-x-10-ecc-mzl500ara221-p289216.html?CCOUNTRY=445&LANGUAGE=en&&r=1) has been replaced with [MAL215097102E3](https://www.digikey.at/de/products/detail/vishay-beyschlag-draloric-bc-components/MAL215097102E3/5635408) due to availability reasons (on DigiKey).

I did not find D1/D2 (Schottky-Diodes) on the exported schematic - am I blind?

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave:

Is this ready to merge?

**Comment by generationmake** [comment]
Hi @aentinger 
let me do some basic tests and then i will merge.

**Pull request merged**
